// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwlb_CBeMrN7n_MgoIDlvFThhAJ2ywjtY',
    appId: '1:206750639647:web:f37d22ecdffab39774572a',
    messagingSenderId: '206750639647',
    projectId: 'katar-khayrak',
    authDomain: 'katar-khayrak.firebaseapp.com',
    storageBucket: 'katar-khayrak.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbfHVAFm7_Wojt5Rm1npAi2rc39jR3vuQ',
    appId: '1:206750639647:android:19bd7875804fe5be74572a',
    messagingSenderId: '206750639647',
    projectId: 'katar-khayrak',
    storageBucket: 'katar-khayrak.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA76TEioHIgd8Ha-qUiln2z2w8_NGVcdoM',
    appId: '1:206750639647:ios:68dd4469d1e2a0f474572a',
    messagingSenderId: '206750639647',
    projectId: 'katar-khayrak',
    storageBucket: 'katar-khayrak.firebasestorage.app',
    iosBundleId: 'com.katarkhayrak.katarKhayrak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA76TEioHIgd8Ha-qUiln2z2w8_NGVcdoM',
    appId: '1:206750639647:ios:68dd4469d1e2a0f474572a',
    messagingSenderId: '206750639647',
    projectId: 'katar-khayrak',
    storageBucket: 'katar-khayrak.firebasestorage.app',
    iosBundleId: 'com.katarkhayrak.katarKhayrak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwlb_CBeMrN7n_MgoIDlvFThhAJ2ywjtY',
    appId: '1:206750639647:web:761a5654debc349774572a',
    messagingSenderId: '206750639647',
    projectId: 'katar-khayrak',
    authDomain: 'katar-khayrak.firebaseapp.com',
    storageBucket: 'katar-khayrak.firebasestorage.app',
  );
}